# Generated by Django 6.0.3 on 2026-04-04 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=389)),
                ('use_tls', models.BooleanField(default=False)),
                ('bind_dn', models.CharField(max_length=512)),
                ('bind_password', models.CharField(max_length=512)),
                ('base_dn', models.CharField(max_length=512)),
                ('user_filter', models.CharField(default='(objectClass=person)', max_length=512)),
                ('group_filter', models.CharField(default='(objectClass=group)', max_length=512)),
                ('sync_interval_minutes', models.IntegerField(default=60)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
