# Generated by Django 6.0.3 on 2026-04-04 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSOProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('microsoft', 'Microsoft'), ('google', 'Google'), ('oidc', 'OpenID Connect'), ('adfs', 'ADFS')], max_length=20)),
                ('client_id', models.CharField(max_length=512)),
                ('client_secret', models.CharField(max_length=512)),
                ('tenant_id', models.CharField(blank=True, default='', max_length=255)),
                ('discovery_url', models.URLField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=False)),
                ('allow_registration', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
