# Generated by Django 6.0.3 on 2026-07-12 19:20

import apps.resources.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='data',
            field=apps.resources.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='secrethistory',
            name='data',
            field=apps.resources.fields.EncryptedTextField(),
        ),
    ]
