# Generated by Django 6.0.3 on 2026-04-04 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('aco', models.CharField(max_length=64)),
                ('aco_foreign_key', models.UUIDField()),
                ('aro', models.CharField(max_length=64)),
                ('aro_foreign_key', models.UUIDField()),
                ('type', models.IntegerField(choices=[(1, 'Read'), (7, 'Update'), (15, 'Owner')], default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['aco', 'aco_foreign_key'], name='sharing_per_aco_28bce2_idx'), models.Index(fields=['aro', 'aro_foreign_key'], name='sharing_per_aro_0d8219_idx')],
                'unique_together': {('aco', 'aco_foreign_key', 'aro', 'aro_foreign_key')},
            },
        ),
    ]
