# Generated by Django 6.0.3 on 2026-04-04 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('storage_key', models.CharField(db_index=True, max_length=512, unique=True)),
                ('size_bytes', models.BigIntegerField()),
                ('original_name_encrypted', models.TextField()),
                ('mime_category', models.CharField(choices=[('document', 'Documento'), ('image', 'Imagem'), ('archive', 'Arquivo compactado'), ('key', 'Chave / Certificado'), ('spreadsheet', 'Planilha'), ('other', 'Outro')], default='other', max_length=32)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('encryption_version', models.CharField(choices=[('openpgp-aes256gcm-v1', 'OpenPGP + AES-256-GCM v1')], default='openpgp-aes256gcm-v1', max_length=32)),
                ('upload_completed', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_files', to=settings.AUTH_USER_MODEL)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_resource', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload iniciado'), ('UPLOAD_CONFIRMED', 'Upload confirmado'), ('DOWNLOAD', 'Download (URL pré-assinada gerada)'), ('DELETE', 'Arquivo deletado'), ('SHARE', 'Arquivo compartilhado'), ('REVOKE', 'Acesso revogado')], max_length=32)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('presigned_url_expires_at', models.DateTimeField(blank=True, null=True)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_file_shares', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_access_logs', to=settings.AUTH_USER_MODEL)),
                ('file_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='files.fileresource')),
            ],
            options={
                'verbose_name': 'Log de Acesso a Arquivo',
                'verbose_name_plural': 'Logs de Acesso a Arquivos',
            },
        ),
        migrations.CreateModel(
            name='FileSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_key_encrypted', models.TextField()),
                ('file_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='files.fileresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_secrets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Segredo de Arquivo',
                'verbose_name_plural': 'Segredos de Arquivo',
            },
        ),
        migrations.AddIndex(
            model_name='fileresource',
            index=models.Index(fields=['upload_completed', 'created_at'], name='files_filer_upload__98ddcd_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['file_resource', 'created_at'], name='files_filea_file_re_39dc1a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['user', 'action', 'created_at'], name='files_filea_user_id_015050_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filesecret',
            unique_together={('file_resource', 'user')},
        ),
    ]
