# Generated by Django 6.0.3 on 2026-07-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresource',
            name='encryption_version',
            field=models.CharField(choices=[('openpgp-aes256gcm-v1', 'OpenPGP + AES-256-GCM v1'), ('fernet-v1', 'Fernet (cifragem em repouso no servidor) v1')], default='openpgp-aes256gcm-v1', max_length=32),
        ),
    ]
